server:
  port: 8080
spring:
  application:
    name: water-consumption-service
  cloud:
    config:
      profile: prod
  config:
    import: optional:configserver:http://localhost:8888/
  
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
water-consumption-service:
  irrigation-area: 500.0
  applied-blade: 2.0